yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'post'

urlpatterns = [
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:SlugField>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='post')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок',
                             max_length=200,
                             help_text='Название группы')
    slug = models.SlugField('Адрес URLа', unique=True, help_text='URL группы')
    description = models.TextField('Описание', help_text='Описание группы')

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups4all',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Выберите картинку'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField('Текст комментария',
                            help_text='Введите текст комментария')

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='one_following'),
            models.CheckConstraint(check=~models.Q(user=models.F('author')),
                                   name='user_not_author')
        ]

    def __str__(self) -> str:
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['group'].required = False


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from yatube.settings import POSTS_ON_THE_PAGES

from .models import Follow, Group, Post, User
from posts.forms import CommentForm, PostForm


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, SlugField):
    group = get_object_or_404(Group, slug=SlugField)
    posts = group.groups4all.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    following = False
    if request.user.is_authenticated:
        author = User.objects.get(username=username)
        follow = Follow.objects.filter(user=request.user, author=author)
        if len(follow) != 0:
            following = True
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'username': user,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, id=post_id)
        comment.save()
    return redirect(reverse('post:post_detail', args=[post_id]))


def post_detail(request, post_id):
    is_edit = False
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None,)
    if request.method == 'POST':
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = request.post
            comment.save()
            return redirect(reverse('post:post_detail', args=[post_id]))
        else:
            return render(request, reverse('post:post_detail', args=[post_id]),
                          {'form': form, })

    if post.author == request.user:
        is_edit = True
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('post:profile',
                            args=[request.user.username]))
        else:
            return render(request, 'posts/create_post.html',
                          {'form': form, 'is_edit': is_edit})

    form = {'form': form, 'is_edit': is_edit}
    return render(request, 'posts/create_post.html', form)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if post.author == request.user:
        is_edit = True
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return redirect(reverse('post:post_detail', args=[post_id]))
            else:
                return render(request, 'posts/create_post.html',
                              {'form': form, 'is_edit': is_edit})
        form = {'form': form, 'is_edit': is_edit}
        return render(request, 'posts/create_post.html', form)
    else:
        return redirect(reverse('post:post_detail', args=[post_id]))


@login_required
def follow_index(request):
    follow = Follow.objects.filter(user=request.user)
    follow_list = follow.values_list('author')
    posts = Post.objects.filter(author__in=follow_list)
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    if (request.user == author
            or request.user.follower.filter(author=author).exists()):
        return redirect(reverse('post:profile', args=[username]))

    Follow.objects.create(user=request.user, author=author)
    return redirect(reverse('post:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    follow = Follow.objects.get(user=request.user, author=author)
    follow.delete()
    return redirect(reverse('post:profile', args=[username]))

yatube/templates/posts/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
    <form method="post" action="{% url 'post:add_comment' post.id %}">
      {% csrf_token %}      
      <div class="form-group mb-2">
        {{ form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
{% endif %}
<h5 class="card-header">Комментарии:</h5>
{% for comment in comments %}
<div class="media mb-4">
  <div class="media-body">
    <h5 class="mt-0">
      <a href="{% url 'post:profile' comment.author.username %}">
        {{ comment.author.username }}
      </a>
    </h5>
      <p>
       {{ comment.text|linebreaksbr }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/posts/includes/following.html
{% if following %}
<a
  class="btn btn-lg btn-light"
  href="{% url 'post:profile_unfollow' username %}" role="button"
>
  Отписаться
</a>
{% else %}
  <a
    class="btn btn-lg btn-primary"
    href="{% url 'post:profile_follow' username %}" role="button"
  >
    Подписаться
  </a>
{% endif %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %} 

yatube/templates/posts/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
  {% if user.is_authenticated %}
      <div class="row my-3">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name  == 'post:index' %}active{% endif %}"
              href="{% url 'post:index' %}"
            >
              Все авторы
            </a>
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name  == 'post:follow_index' %}active{% endif %}"
              href="{% url 'post:follow_index' %}"
            >
              Избранные авторы
            </a>
          </li>
        </ul>
      </div>
    {% endif %}
{% endwith %} 