yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'post'

urlpatterns = [
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:SlugField>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='post')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок',
                             max_length=200,
                             help_text='Название группы')
    slug = models.SlugField('Адрес URLа', unique=True, help_text='URL группы')
    description = models.TextField('Описание', help_text='Описание группы')

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups4all',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Выберите картинку'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField('Текст комментария',
                            help_text='Введите текст комментария')

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='one_following'),
            models.CheckConstraint(check=~models.Q(user=models.F('author')),
                                   name='user_not_author')
        ]

    def __str__(self) -> str:
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['group'].required = False


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from yatube.settings import POSTS_ON_THE_PAGES

from .models import Follow, Group, Post, User
from posts.forms import CommentForm, PostForm


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, SlugField):
    group = get_object_or_404(Group, slug=SlugField)
    posts = group.groups4all.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    following = False
    if request.user.is_authenticated:
        author = User.objects.get(username=username)
        follow = Follow.objects.filter(user=request.user, author=author)
        if len(follow) != 0:
            following = True
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'username': user,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, id=post_id)
        comment.save()
    return redirect(reverse('post:post_detail', args=[post_id]))


def post_detail(request, post_id):
    is_edit = False
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None,)
    if request.method == 'POST':
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = request.post
            comment.save()
            return redirect(reverse('post:post_detail', args=[post_id]))
        else:
            return render(request, reverse('post:post_detail', args=[post_id]),
                          {'form': form, })

    if post.author == request.user:
        is_edit = True
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('post:profile',
                            args=[request.user.username]))
        else:
            return render(request, 'posts/create_post.html',
                          {'form': form, 'is_edit': is_edit})

    form = {'form': form, 'is_edit': is_edit}
    return render(request, 'posts/create_post.html', form)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if post.author == request.user:
        is_edit = True
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return redirect(reverse('post:post_detail', args=[post_id]))
            else:
                return render(request, 'posts/create_post.html',
                              {'form': form, 'is_edit': is_edit})
        form = {'form': form, 'is_edit': is_edit}
        return render(request, 'posts/create_post.html', form)
    else:
        return redirect(reverse('post:post_detail', args=[post_id]))


@login_required
def follow_index(request):
    follow = Follow.objects.filter(user=request.user)
    follow_list = follow.values_list('author')
    posts = Post.objects.filter(author__in=follow_list)
    paginator = Paginator(posts, POSTS_ON_THE_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    if (request.user == author
            or request.user.follower.filter(author=author).exists()):
        return redirect(reverse('post:profile', args=[username]))

    Follow.objects.create(user=request.user, author=author)
    return redirect(reverse('post:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    follow = Follow.objects.get(user=request.user, author=author)
    follow.delete()
    return redirect(reverse('post:profile', args=[username]))

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  <title>
    {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} 
  </title>
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header"> 
            Новый пост 
          </div>
          <div class="card-body">
            {% load user_filters %}
                {% if form.errors %}
                    {% for field in form %} 
                      {% for error in field.errors %}
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                {% endif %}

                <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:"form-control" }} 
                      {% if field.help_text %}
                        <small 
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                  </button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}

{% block title %}
  <title>Подписки</title>
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <h1>Подписки пользователя '{{ user.username }}'</h1>

  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
      {% if post.author.get_full_name %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author.get_full_name }} </a>
      {% else %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author }} </a>
      {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'post:post_detail' post.id %}">подробная информация </a></p>
    {% if post.group %} 
      <a href="{% url 'post:group_list' post.group.slug %}">все записи группы - <b>{{post.group}}</b></a>
    {% endif%}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 

  {% include "posts/includes/paginator.html" %} 
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  <title>{{group}}</title>
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <h1>{{group}}</h1>
    <h5><p>{{ group.description }}</p></h5>
  {% for post in page_obj %}
    <ul>
      <li>
      {% if post.author.get_full_name %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author.get_full_name }} </a>
      {% else %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author }} </a>
      {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'post:post_detail' post.id %}">подробная информация </a></p> 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}

{% block title %}
  <title>Последние обновления на сайте</title>
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
  {% cache 20 index_page %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
      {% if post.author.get_full_name %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author.get_full_name }} </a>
      {% else %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author }} </a>
      {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'post:post_detail' post.id %}">подробная информация </a></p>
    {% if post.group %} 
      <a href="{% url 'post:group_list' post.group.slug %}">все записи группы - <b>{{post.group}}</b></a>
    {% endif%}
    <p align="right"><a class="btn btn-lg btn-primary" href="#top" role="button">Наверх</a></p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% endcache %} 
  {% include "posts/includes/paginator.html" %} 
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
  {% block title %}
    <title>{{ post.text|truncatechars:30 }}</title>
  {% endblock title %} 
  {% block content %}
  <div class="container py-5">
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y"}}
      </li>
      <li>
        Группа: 
          {% if post.group %} 
            {{ post.group }} 
            <a href="{% url 'post:group_list' post.group.slug %}">все записи группы {{post.group}}</a>
          {% endif%}
      </li>
      <li>
      {% if post.author.get_full_name %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author.get_full_name }} </a>
      {% else %}
        Автор: <a href="{% url 'post:profile' post.author %}"> {{ post.author }} </a>
      {% endif %}
      </li>
      <li>
        Всего постов автора: <span > {{ post.author.posts.count }} </span>
      </li>
      <li>
        <a href="{% url 'post:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }} 
      </p>
      {% if is_edit %}
        <a href="{% url 'post:post_edit' post.id %}"> Редактировать статью </a>
      {% endif %}
    </article>
    <hr>
    {% include 'posts/includes/comments.html' with comments=post.comments.all form_comment=form_comment post=post %}
</div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
    <title>Профайл пользователя 
      {{ username }} 
    </title>

{% endblock title %} 
{% block content %}
<div class="container py-5">
  <h1>Все посты пользователя {{ username }} </h1>
  <h3>Всего постов: {{ username.posts.count }} </h3>
  {% if user != username %}
    {% include 'posts/includes/following.html' %}
  {% endif%}
  
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ username }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}   
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'post:post_detail' post.id %}">подробная информация </a></p> 
    {% if post.group %} 
      <a href="{% url 'post:group_list' post.group.slug %}">все записи группы {{post.group}}</a>
    {% endif%}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %} 
</div>
{% endblock content %}